name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  GIT_USER: fengit
  GIT_EMAIL: fengit@outlook.com
  THEME_REPO: blinkfox/hexo-theme-matery
  THEME_BRANCH: develop
  DEPLOY_REPO: hmilyfyj/hmilyfyj.github.io
  DEPLOY_BRANCH: master
  DEPLOY_REPO1: git@e.coding.net:AIW/AIW.git
  DEPLOY_BRANCH1: coding-pages

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [14.x]

    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install dependencies
        run: |
          mkdir build && cd build
          npm i -g hexo-cli
          hexo init
          npm install
          npm install hexo-deployer-git --save


      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
          HEXO_CONFIG: ${{secrets.HEXO_CONFIG}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          echo "$HEXO_CONFIG" > _config.yml 
          rm -rf source/_posts
          git clone git@github.com:hmilyfyj/Note.git source/_posts
          mkdir source/media && mkdir source/images && cp ./source/_posts/images/* ./source/images && cp ./source/_posts/media/* ./source/media
          rm -rf _posts/.travis
          rm -rf _posts/.travis.yml
          rm -rf _posts/.git
        working-directory: ./build
        
      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: build/themes/hexo-theme-matery
          
      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
          HEXO_CONFIG: ${{secrets.HEXO_CONFIG}}
        run: |
          mv source/_posts/_config.theme.yml themes/hexo-theme-matery/_config.yml
          # cp -frp source/_posts/scaffolds/* scaffolds/
          # cp -frp source/_posts/source/* source/
          #rm -rf source/_posts/scaffolds
          #rm -rf source/_posts/source
        working-directory: ./build

      - name: generate
        run: |
          hexo clean
          hexo generate
          touch CNAME
          echo "b.fengbl.cn" > CNAME
          ls -lh
        working-directory: ./build
      - name: Deploy hexo
        run: |
          hexo d
          #npm run deploy
        working-directory: ./build
