name: CI

on:
  push:
    branches:
      - master

env:
  GIT_USER: fengit
  GIT_EMAIL: fengit@outlook.com
  THEME_REPO: blinkfox/hexo-theme-matery
  THEME_BRANCH: master
  DEPLOY_REPO: hmilyfyj/hmilyfyj.github.io
  DEPLOY_BRANCH: test

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [10.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout theme repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: themes/hexo-theme-matery

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
          HEXO_CONFIG: ${{secrets.HEXO_CONFIG}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          echo "$HEXO_CONFIG" > _config.yml 
          
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
          #npm install

      - name: Deploy hexo
        run: |
          npm run deploy
